export const concepts = [
  { id: 'windows', name: 'Little windows', descriptor: 'A few useful things, beautifully framed.', mood: 'An illustrated field guide', colors: ['#fbf7ef','#a8b69a','#e9b38d'], seed: 'TgLLiH0i4K2ROP56vnc6vpm2QZEM5vysXrrRJNpHZFrpllr6qi2UzMCuS8IoaM28VLzPLKGqC7fiTpr7ERfXrYmbLOsjb1rn', spark: 'Repeated vertical strokes become window frames; ROP56 suggests a photographic contact sheet.' },
  { id: 'home', name: 'A home within reach', descriptor: 'See the possibilities in everyday spaces.', mood: 'A little home to explore', colors: ['#f3ebdd','#b9684f','#71794e'], seed: 'QlqfroSWXSG7kccJUwsJRvtLqJLLvPGdfkddY1sFi3piXCtU2vQRGyMIOCMYcgcd7G9yAxHCtrURdNCJ6KeAWK78kCB9diuD', spark: 'Paired letters suggest adjoining rooms, and alternating letterforms suggest a floor plan.' },
  { id: 'paths', name: 'Paths of discovery', descriptor: 'Follow a little curiosity.', mood: 'Choose a path through their interests', colors: ['#f5f0df','#355c50','#c39943'], seed: 'ntBLtF0rkYt4JBknjUYBgR61JxK6uNJ3JDjwuxi9aec7gP5wMyNvnSjAjtaZahI56vM2OJ50itCGdOgmTdIgMPZmO6VfeG6G', spark: 'F0rk suggests branching paths; returning sixes suggest revisiting familiar ideas.' },
  { id: 'stars', name: 'Small constellations', descriptor: 'Little ideas that belong together.', mood: 'Connect the everyday dots', colors: ['#f7f5ee','#29394d','#c3a261'], seed: 'o7K8wWh6rmdzFbkpV99c8F4kb8PKZiYfu5HgHqv1BhGLFe6LwNRz5M1ePon8zZD0AuyGTzrdgEjB0rELSI3n6JDGM8g6j35t', spark: 'Clusters of numbers suggest constellations: distinct points forming a small whole.' },
  { id: 'paper', name: 'Paper play', descriptor: 'Small invitations. Big discoveries.', mood: 'A world of cut-paper possibilities', colors: ['#fff4de','#c95c42','#426493'], seed: 'o3aTcPFmPuzyOQuUoveCRngWtzAwm8vUrqeHDlWJcnKKCYai5BbeIRn4A0mJxl3bmrU4CvCIGVaR3D54a0KUVwu6SUTUap2j', spark: 'Rounded letters interrupted by angular capitals become layered paper shapes; 3D suggests depth.' },
  { id: 'rhythms', name: 'Everyday rhythms', descriptor: 'Meet them in the moments you already share.', mood: 'Find a little room in your day', colors: ['#f4eddf','#665064','#c9d775'], seed: 'OSMe1h5kjabFH4FbGYi18Ne0n5YWZH45aD4HSfN9Sq14Cqf7Y4UJoPaQFm3q4yHzWmHemQ3nwtG9124z8JQZywQnXnhkBKfc', spark: 'Ne0n suggests a luminous accent; number groups suggest recurring moments, without a prescribed timetable.' },
  { id: 'notebook', name: 'The observation notebook', descriptor: 'Look a little closer.', mood: 'Notice first. Offer next.', colors: ['#f8f4e9','#7396ab','#89936b'], seed: 'l7RDFFHmI14lLiN8LnNGDSJUYvNrOjdZdnNfnBhWHkZBpeBVV4HTNTfCnHbQcgEIwdyd3cju72SvzCD5OeiVR287gSLpEAdq', spark: 'Repeated strokes become notebook rulings; paired capitals suggest a sketch beside an observation.' },
  { id: 'ribbon', name: 'The unfolding ribbon', descriptor: 'Growing, one discovery at a time.', mood: 'See how familiar ideas grow', colors: ['#faf6ec','#467d79','#cc8270'], seed: '3Hv28y45TA5jubEpYDG3gfM8vnkRySCO2wHTF7OwJt6pv6CWIgvNCIeOsLwehDh5jmsLdqahpd8XsDmh8klDc6SlKrzSHkUD', spark: 'The opening number sequence suggests changing intervals; repeated eights suggest continuity.' },
  { id: 'gallery', name: 'The quiet gallery', descriptor: 'Make room for one small thing.', mood: 'One idea, thoughtfully seen', colors: ['#f6f3ec','#cfada1','#92a99b'], seed: 'lcPQbVg4JEmTFcKkGSjPe0fmhM2uOvmIhYGHsfjaboqgQUAQbzveJf2xmUrOf6xrXJDnLt9V1bEtLgs4otRtCWXn15TGjTKt', spark: 'Changing letter heights suggest shifts in scale; QUAQ becomes a framed centerpiece.' },
  { id: 'together', name: 'Together, in small steps', descriptor: 'A little less telling. A little more showing.', mood: 'Everyday moments, frame by frame', colors: ['#f7eedf','#505b83','#d7aa4e'], seed: 'gtTJls6E1b9QpyFBKQEWAzuR4d6zCCnQmxYSKvPAarw9c3jhncAXGxs7mWiHozfKNI1NGaDklz2QAz4j3hcSJmCjgnzvK6v5', spark: 'Paired letters suggest adult and child; descending 4j3 suggests breaking a task into smaller steps.' },
];
export const stages = [
  { id:'0-3',label:'0–3 months' }, { id:'3-6',label:'3–6 months' }, { id:'6-9',label:'6–9 months',ready:true },
  { id:'9-12',label:'9–12 months' }, { id:'12-18',label:'12–18 months' }, { id:'18-24',label:'18–24 months',ready:true }, { id:'24-36',label:'2–3 years' },
];
