name: Deploy Terminal Desires Ranker App

on:
  push:
    paths:
      - 'terminal-desires-ranker/**'  # Only trigger when files in terminal-desires-ranker directory change
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'terminal-desires-ranker/package-lock.json'

      - name: Install Dependencies
        working-directory: terminal-desires-ranker
        run: npm install

      - name: Build
        working-directory: terminal-desires-ranker
        run: npm run build

      - name: Checkout gh-pages
        run: |
          # Save built files
          mv terminal-desires-ranker/dist ./dist-temp
          
          # Fetch and checkout gh-pages
          git fetch origin gh-pages
          git checkout gh-pages
          
          # Clean and copy new build
          rm -rf terminal-desires-ranker
          mkdir -p terminal-desires-ranker
          cp -r dist-temp/* terminal-desires-ranker/
          rm -rf dist-temp
          
          # Configure Git and commit
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git add -f terminal-desires-ranker
          git commit -m "Deploy Terminal Desires Ranker app to GitHub Pages" || echo "No changes to commit"
          git push origin gh-pages
