name: Deploy Jekyll Site

on:
  push:
    branches: [main]
    paths-ignore: ['terminal-desires-ranker/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: ./
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf docs/*
          mv _site docs
          touch docs/.nojekyll
          git add -f docs
          git commit -m "Deploy Jekyll site to GitHub Pages" || echo "No changes"
          git push origin gh-pages