name: Deploy Terminal Desires Ranker App

on:
  push:
    paths:
      - 'terminal-desires-ranker/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'terminal-desires-ranker/package-lock.json'
      - name: Install Dependencies
        working-directory: terminal-desires-ranker
        run: npm install
      - name: Build
        working-directory: terminal-desires-ranker
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: terminal-desires-ranker/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: terminal-desires-ranker
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f terminal-desires-ranker
          git commit -m "Deploy Terminal Desires Ranker app to GitHub Pages" || echo "No changes"
          git push origin gh-pages
