name: Deploy Terminal Desires Ranker App
on:
  push:
    paths:
      - 'terminal-desires-ranker/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'terminal-desires-ranker/package-lock.json'
      - name: Install Dependencies
        working-directory: terminal-desires-ranker
        run: npm install
      - name: Build
        working-directory: terminal-desires-ranker
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: terminal-desires-ranker/dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
